---
version: "3"
services:
  {{ coredns_servicename }}:
    image: "{{ coredns_docker_image_name }}:{{ coredns_docker_image_version }}"
    restart: always
    command: -conf /etc/coredns/Corefile
    volumes:
      - "${PWD}:/etc/coredns:ro"
    ports:
      - "{{ coredns_bindip_udp }}:{{ coredns_bindport_udp }}:53/udp"
      - "{{ coredns_bindip_tcp }}:{{ coredns_bindport_tcp }}:53/tcp"
      - "{{ coredns_bindip_metrics }}:{{ coredns_bindport_metrics }}:9153/tcp"
    networks:
      - metrics
        
    labels:
      prometheus-job: coredns
      prometheus-port: 9153
      prometheus-path: /metrics
      io.prometheus.metrics.ip: "{{ coredns_bindip_metrics }}"
      io.prometheus.metrics.port: "{{ coredns_bindport_metrics }}"
      io.prometheus.metrics.path: "/metrics"
    hostname: "{{ coredns_servicename }}.{{ inventory_hostname }}"

networks:
  metrics:
    name: metrics_network