- name: Create firewall profile 'ssh-only'
  hetzner.hcloud.hcloud_firewall:
    api_token: "{{ api_token }}"
    state: "{{ state }}"
    name: ssh-only
    rules:
    - direction: in
      protocol: tcp
      port: "22"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow ssh in

- name: Create firewall profile 'class_stunturn'
  hetzner.hcloud.hcloud_firewall:
    api_token: "{{ api_token }}"
    state: "{{ state }}"
    name: class_stunturn
    rules:
    - direction: in
      protocol: tcp
      port: "3478"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow stun/tcp plain in

    - direction: in
      protocol: udp
      port: "3478"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow turn/udp plain in

    - direction: in
      protocol: tcp
      port: "5349"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow stun/tcp tls in

    - direction: in
      protocol: udp
      port: "49152-65535"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow turn media udp in

    - direction: in
      protocol: tcp
      port: "22"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow ssh in

    - direction: in
      protocol: udp
      port: "10001"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow wireguard in

    - direction: in
      protocol: icmp
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow icmp/ping in


- name: Create firewall profile 'class_front'
  hetzner.hcloud.hcloud_firewall:
    api_token: "{{ api_token }}"
    state: "{{ state }}"
    name: class_front
    rules:

    - direction: in
      protocol: tcp
      port: "53"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow dns tcp in

    - direction: in
      protocol: udp
      port: "53"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow dns udp in

    - direction: in
      protocol: tcp
      port: "80"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow http in

    - direction: in
      protocol: tcp
      port: "443"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow https in

    - direction: in
      protocol: tcp
      port: "22"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow ssh in

    - direction: in
      protocol: udp
      port: "10001"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow wireguard in

    - direction: in
      protocol: icmp
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow icmp/ping in

- name: Create firewall profile 'class_admin'
  hetzner.hcloud.hcloud_firewall:
    api_token: "{{ api_token }}"
    state: "{{ state }}"
    name: class_admin
    rules:
    - direction: in
      protocol: tcp
      port: "22"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow ssh in

    - direction: in
      protocol: udp
      port: "10001"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow wireguard in

    - direction: in
      protocol: icmp
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow icmp/ping in


- name: Create firewall profile 'class_opentalk'
  hetzner.hcloud.hcloud_firewall:
    api_token: "{{ api_token }}"
    state: "{{ state }}"
    name: class_opentalk
    rules:

    - direction: in
      protocol: tcp
      port: "80"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow http in

    - direction: in
      protocol: tcp
      port: "443"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow https in

    - direction: in
      protocol: tcp
      port: "22"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow ssh in

    - direction: in
      protocol: udp
      port: "10001"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow wireguard in

    - direction: in
      protocol: icmp
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow icmp/ping in


- name: Create firewall profile 'class_jitsi'
  hetzner.hcloud.hcloud_firewall:
    api_token: "{{ api_token }}"
    state: "{{ state }}"
    name: class_jitsi
    rules:

    - direction: in
      protocol: tcp
      port: "80"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow http in

    - direction: in
      protocol: tcp
      port: "443"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow https in

    - direction: in
      protocol: tcp
      port: "4443"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow in for RTP media over TCP

    - direction: in
      protocol: udp
      port: "10000"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow in for RTP media over UDP

    - direction: in
      protocol: tcp
      port: "22"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow ssh in

    - direction: in
      protocol: udp
      port: "10001"
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow wireguard in

    - direction: in
      protocol: icmp
      source_ips:
        - 0.0.0.0/0
        - ::/0
      description: allow icmp/ping in
