---
# tasks file for cyberdinge.nodeexporter

- name: install prometheus-node-exporter via apt
  apt:
    state: present
    name: prometheus-node-exporter

- name: Set systemd ARGS
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-node-exporter
    state: "present"
    regexp: '^ARGS="'
    line: 'ARGS=" --web.listen-address="{{ nodeexporter_bindip }}:{{ nodeexporter_bindport }}" '

- name: Enable service prometheus-node-exporter and ensure it is enabled and restarted and not masked
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: yes
    masked: no
    state: restarted

- name: set facts to notify prometheus about the scrape target
  ansible.builtin.set_fact:
    scrape_target_state: present
    scrape_target_job: node_exporter
    scrape_target_hostname: "{{ inventory_hostname }}"
    scrape_target_domain: "{{ project_domain }}"    
    scrape_target_network: "{{ wireguard_network_name }}"
    scrape_target_url: "{{ hostvars[inventory_hostname].wireguard_address }}:{{ nodeexporter_bindport }}"
  changed_when: true # handler running when somethingchanged
  notify:
    - "prometheus - add static scrape file"

- name: Flush handlers
  meta: flush_handlers
