---
# tasks file for cyberdinge.users
- name: creating users
  with_items: "{{ users }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /bin/bash

- name: Set authorized key taken from vars
  with_items: "{{ users }}"
  when: item.state == "present"
  authorized_key:
    user: "{{ item.name }}"
    state: "{{ item.state }}"
    key: "{{ item.key }}"

- name: set sudo without password
  with_items: "{{ users }}"
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/sudoers
    create: yes
    state: "{% if item.sudoer %}present{% else %}absent{% endif %}"
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} ALL=(ALL) NOPASSWD:ALL'   

- name: set bash promt PS1 for users
  with_items: "{{ users }}"
  when: item.state == "present"
  ansible.builtin.lineinfile: 
    path: "/home/{{ item.name }}/.bashrc"
    regex: "^#force_color_prompt=yes"
    line: 'force_color_prompt=yes'