installdir: /dockerstacks/promtail
docker_image: grafana/promtail:latest
promtail_loki_url: http://loki:3100/loki/api/v1/push
promtail_http_listen_port: 9080
promtail_grpc_listen_port: 0
promtail_state: present