wireguardui_installdir: /dockerstacks/wireguardui
wireguardui_docker_image: ngoduykhanh/wireguard-ui:latest
wireguardui_servicename: wireguardui
traefik_providers_docker_network: traefik_proxy
wireguardui_domain: "wireguardui.{{ inventory_hostname }}.{{ project_domain }}"
wireguardui_state: present

wireguardui_wg_listen_port: 5000
wireguardui_admin_listen_ip: 0.0.0.0
wireguardui_admin_listen_port: 8086
wireguardui_configfilepath: /etc/wireguard/wg0.conf

# The default endpoint address used in global settings. (default is your public IP address)
wireguardui_endpoint_address: 127.0.0.1

# SESSION_SECRET	Used to encrypt the session cookies. Set this to a random value.
WGUI_SESSION_SECRET: 8s7d6nf8s7d6nf8s7d6fn87ae6n8w7e6rn8

# WGUI_USERNAME	The username for the login page. (default admin)
WGUI_USERNAME: admin

# WGUI_PASSWORD	The password for the user on the login page. Will be hashed automatically. (default admin)
WGUI_PASSWORD: change_this_to_something_different

# WGUI_PASSWORD_HASH	The password hash for the user on the login page. (alternative to WGUI_PASSWORD)
WGUI_PASSWORD_HASH:

# WGUI_ENDPOINT_ADDRESS	The default endpoint address used in global settings. (default is your public IP address)
WGUI_ENDPOINT_ADDRESS: 0.0.0.0

# WGUI_DNS	The default DNS servers (comma-separated-list) used in the global settings. (default 1.1.1.1)
WGUI_DNS: 1.1.1.1

# WGUI_MTU	The default MTU used in global settings. (default 1450)
WGUI_MTU: 1450

# WGUI_PERSISTENT_KEEPALIVE	The default persistent keepalive for WireGuard in global settings. (default 15)
WGUI_PERSISTENT_KEEPALIVE: 15

# WGUI_FORWARD_MARK	The default WireGuard forward mark. (default 0xca6c)
WGUI_FORWARD_MARK: 0xca6c

# WGUI_CONFIG_FILE_PATH	The default WireGuard config file path used in global settings. (default /etc/wireguard/wg0.conf)
WGUI_CONFIG_FILE_PATH: /etc/wireguard/wg0.conf

# BASE_PATH	Set this variable if you run wireguard-ui under a subpath of your reverse proxy virtual host (e.g. /wireguard))
BASE_PATH: /wireguard

# Defaults for server configuration
# These environment variables are used to control the default server settings used when initializing the database.

# WGUI_SERVER_INTERFACE_ADDRESSES	The default interface addresses (comma-separated-list) for the WireGuard server configuration. (default 10.252.1.0/24)
WGUI_SERVER_INTERFACE_ADDRESSES: 10.252.1.0/24

# WGUI_SERVER_LISTEN_PORT	The default server listen port. (default 51820)
WGUI_SERVER_LISTEN_PORT: 51820

# WGUI_SERVER_POST_UP_SCRIPT	The default server post-up script.
WGUI_SERVER_POST_UP_SCRIPT: iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

# WGUI_SERVER_POST_DOWN_SCRIPT	The default server post-down script.
WGUI_SERVER_POST_DOWN_SCRIPT: iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Defaults for new clients
# These environment variables are used to set the defaults used in New Client dialog.

# Variable	Description
# WGUI_DEFAULT_CLIENT_ALLOWED_IPS	Comma-separated-list of CIDRs for the Allowed IPs field. (default 0.0.0.0/0)
WGUI_DEFAULT_CLIENT_ALLOWED_IPS: 0.0.0.0/0

# WGUI_DEFAULT_CLIENT_EXTRA_ALLOWED_IPS	Comma-separated-list of CIDRs for the Extra Allowed IPs field. (default empty)
WGUI_DEFAULT_CLIENT_EXTRA_ALLOWED_IPS: 

# WGUI_DEFAULT_CLIENT_USE_SERVER_DNS	Boolean value [0, f, F, false, False, FALSE, 1, t, T, true, True, TRUE] (default true)
WGUI_DEFAULT_CLIENT_USE_SERVER_DNS: true

# WGUI_DEFAULT_CLIENT_ENABLE_AFTER_CREATION	Boolean value [0, f, F, false, False, FALSE, 1, t, T, true, True, TRUE] (default true)
WGUI_DEFAULT_CLIENT_ENABLE_AFTER_CREATION: true

# Email configuration
# To use custom wg.conf template set the WG_CONF_TEMPLATE environment variable to a path to such file. Make sure wireguard-ui will be able to work with it - use default template for reference.
# In order to sent the wireguard configuration to clients via email, set the following environment variables:

# using SendGrid API
# SENDGRID_API_KEY: Your sendgrid api key
# EMAIL_FROM_ADDRESS: the email address you registered on sendgrid
# EMAIL_FROM_NAME: the sender's email address

# using SMTP
# SMTP_HOSTNAME: The SMTP ip address or hostname
# SMTP_PORT: the SMTP port
# SMTP_USERNAME: the SMTP username to authenticate
# SMTP_PASSWORD: the SMTP user password
# SMTP_AUTH_TYPE: the authentication type. Possible values: PLAIN, LOGIN, NONE
# SMTP_ENCRYPTION: the encryption method. Possible values: SSL, SSLTLS, TLS or STARTTLS (default)
# EMAIL_FROM_ADDRESS: the sender's email address
# EMAIL_FROM_NAME: the sender's name

# WG_CONFIG_TEMPLATE
# WG_CONF_TEMPLATE: |
  # # This file was generated using wireguard-ui (https://github.com/ngoduykhanh/wireguard-ui)
  # # Please don't modify it manually, otherwise your change might get replaced.

  # # Address updated at:     {{ .serverConfig.Interface.UpdatedAt }}
  # # Private Key updated at: {{ .serverConfig.KeyPair.UpdatedAt }}
  # [Interface]
  # Address = {{$first :=true}}{{range .serverConfig.Interface.Addresses }}{{if $first}}{{$first = false}}{{else}},{{end}}{{.}}{{end}}
  # ListenPort = {{ .serverConfig.Interface.ListenPort }}
  # PrivateKey = {{ .serverConfig.KeyPair.PrivateKey }}
  # {{if .globalSettings.MTU}}MTU = {{ .globalSettings.MTU }}{{end}}
  # PostUp = {{ .serverConfig.Interface.PostUp }}
  # PostDown = {{ .serverConfig.Interface.PostDown }}

  # {{range .clientDataList}}{{if eq .Client.Enabled true}}
  # # ID:           {{ .Client.ID }}
  # # Name:         {{ .Client.Name }}
  # # Email:        {{ .Client.Email }}
  # # Created at:   {{ .Client.CreatedAt }}
  # # Update at:    {{ .Client.UpdatedAt }}
  # [Peer]
  # PublicKey = {{ .Client.PublicKey }}
  # {{if .Client.PresharedKey }}PresharedKey = {{ .Client.PresharedKey }}
  # {{end}}AllowedIPs = {{$first :=true}}{{range .Client.AllocatedIPs }}{{if $first}}{{$first = false}}{{else}},{{end}}{{.}}{{end}}{{range .Client.ExtraAllowedIPs }},{{.}}{{end}}
  # {{end}}{{end}}