---
version: "3"
services:
  {{ keycloak_servicename }}:
    image: {{ keycloak_docker_image }}
    restart: always
    user: 0:0
    volumes:
      - "{{ keycloak_installdir }}/data:/opt/keycloak/data:rw"
      - "{{ keycloak_installdir }}/certs:/etc/x509/https:rw"
    environment:
      KEYCLOAK_ADMIN: {{ keycloak_admin_username }}
      KEYCLOAK_ADMIN_PASSWORD: {{ keycloak_admin_password }}
      KEYCLOAK_LOGLEVEL: {{ keycloak_loglevel }}
      KEYCLOAK_FRONTEND_URL: {{ keycloak_frontend_url }}
    command: >
      start
      --https-certificate-file=/etc/x509/https/tls.crt
      --https-certificate-key-file=/etc/x509/https/tls.key
      --https-protocols={{ keycloak_https_protocols }}
      --https-port={{ keycloak_https_port }}
      --hostname={{ keycloak_domain }}
      --hostname-admin={{ keycloak_domain }}
      --proxy=edge

    labels:
      - traefik.enable=true

      - traefik.http.routers.{{ keycloak_servicename }}.rule=Host(`{{ keycloak_domain }}`)
      - traefik.http.routers.{{ keycloak_servicename }}.entrypoints=web
      - traefik.http.routers.{{ keycloak_servicename }}.service={{ keycloak_servicename }}
      - traefik.http.routers.{{ keycloak_servicename }}s.rule=Host(`{{ keycloak_domain }}`)
      - traefik.http.routers.{{ keycloak_servicename }}s.entrypoints=websecure
      - traefik.http.routers.{{ keycloak_servicename }}s.service={{ keycloak_servicename }}
      - traefik.http.routers.{{ keycloak_servicename }}.tls=true
      - traefik.http.routers.{{ keycloak_servicename }}s.tls.certresolver=letsencrypt

      - traefik.http.routers.{{ keycloak_servicename }}_admin.rule=Host(`{{ keycloak_domain_admin }}`)
      - traefik.http.routers.{{ keycloak_servicename }}_admin.entrypoints=web
      - traefik.http.routers.{{ keycloak_servicename }}_admin.service={{ keycloak_servicename }}
      - traefik.http.routers.{{ keycloak_servicename }}_admins.rule=Host(`{{ keycloak_domain_admin }}`)
      - traefik.http.routers.{{ keycloak_servicename }}_admins.entrypoints=websecure
      - traefik.http.routers.{{ keycloak_servicename }}_admins.service={{ keycloak_servicename }}
      - traefik.http.routers.{{ keycloak_servicename }}_admins.tls=true
      - traefik.http.routers.{{ keycloak_servicename }}_admins.tls.certresolver=letsencrypt

      - traefik.http.services.{{ keycloak_servicename }}.loadbalancer.server.port=8080
    networks:
      - {{ traefik_providers_docker_network }}
    hostname: "{{ keycloak_servicename }}.{{ inventory_hostname }}"

networks:
  # network in dem traefik ist, damit dieser hier hin routen kann
  {{ traefik_providers_docker_network }}:
    external: true
