---
groups:
- name: blackbox_exporter
  rules:


  # Alert for expiring SSL Certificates
  - alert: SSLCertExpiringSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 5
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "SSL Certificate expires on {{ $labels.instance}} / {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a SSL Certificate that expires in under 5 Days"

  # Alert for expiring SSL Certificates
  - alert: SSLCertExpiringSoonCritical
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "SSL Certificate expires on {{ $labels.instance}} / {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a SSL Certificate that expires in under 3 Days"

  - alert: WebsiteDoesNotResponse
    expr: probe_success{job="blackbox_2xx"} < 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Blackbox Exporter ({{ $labels.instance}} / {{ $labels.instance }})"
      description: "website not avaible via HTTP/HTTPS for more than 5 minutes"

  - alert: ICMPPingResponse
    expr: probe_success{job="blackbox_icmp"} < 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: 'der Host "{{ $labels.instance}}" antwortet nicht auf Ping'
      description: "Host not avaible via ICMP for more than 5 minutes"
