server:
  http_listen_port: {{ promtail_http_listen_port }}
  grpc_listen_port: {{ promtail_grpc_listen_port }}

positions:
  filename: /data/positions.yaml

clients:
  - url: {{ promtail_loki_url }}

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      hostname: {{ inventory_hostname }}
      __path__: /var/log/*log