---
version: "3"
services:
  {{ opentalk_servicename }}:
    image: traefik/whoami:latest
    restart: always
    volumes:
      - "{{ opentalk_installdir }}/data:/data:rw"

    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ opentalk_servicename }}.rule=Host(`{{ opentalk_domain }}`)
      - traefik.http.routers.{{ opentalk_servicename }}.entrypoints=web
      - traefik.http.routers.{{ opentalk_servicename }}.service={{ opentalk_servicename }}
      - traefik.http.routers.{{ opentalk_servicename }}s.rule=Host(`{{ opentalk_domain }}`)
      - traefik.http.routers.{{ opentalk_servicename }}s.entrypoints=websecure
      - traefik.http.routers.{{ opentalk_servicename }}s.service={{ opentalk_servicename }}
      - traefik.http.routers.{{ opentalk_servicename }}s.tls=true
      - traefik.http.routers.{{ opentalk_servicename }}s.tls.certresolver=letsencrypt
      - traefik.http.services.{{ opentalk_servicename }}.loadbalancer.server.port=80
    networks:
      - {{ traefik_providers_docker_network }}
    hostname: "{{ opentalk_servicename }}.{{ inventory_hostname }}"

networks:
  # network in dem traefik ist, damit dieser hier hin routen kann
  {{ traefik_providers_docker_network }}:
    external: true