# opentalk

- name: create installdir "{{ opentalk_installdir }}"
  file:
    state: directory
    path: "{{ opentalk_installdir }}"


- name: Template compose file to "{{ opentalk_installdir }}/docker-compose.yml"
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ opentalk_installdir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0600'
    force: yes


- name: Create the network for provider.docker (will fail, when already exists, ignore it)
  ignore_errors: true
  changed_when: false
  ansible.builtin.shell: "docker network create {{ traefik_providers_docker_network }}"

- name: Create and start services with compose file in "{{ opentalk_installdir }}"
  changed_when: false
  ansible.builtin.shell:
    cmd: docker compose up -d --remove-orphans
    chdir: "{{ opentalk_installdir }}"
  register: compose_output
