---
version: "3"
services:
  {{ prometheus_servicename }}:
    image: {{ prometheus_docker_image_name }}:{{ prometheus_docker_image_version }}
    restart: always
    command: |
      --config.file="/etc/prometheus/prometheus.yml"
      --storage.tsdb.path="/data/"
      --web.page-title="{{ inventory_hostname }}"
      --storage.tsdb.retention.size={{ prometheus_storage_tsdb_retention_size }}
      --web.enable-admin-api 
      --web.enable-lifecycle
    user: 0:0
    volumes:
      - "{{ prometheus_installdir }}/config:/etc/prometheus:ro"
      - "{{ prometheus_installdir }}/data:/data:rw"
      - "/etc/hosts:/etc/hosts:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "{{ prometheus_bindip_tcp }}:{{ prometheus_bindport_tcp }}:9090/tcp"
    networks:
      - metrics
    hostname: "{{ prometheus_servicename }}.{{ inventory_hostname }}"
    labels:
      prometheus-job: prometheus
      prometheus-port: 9090
      prometheus-path: /metrics

networks:
  metrics:
    name: metrics_network