---
# tasks file for cyberdinge.wireguard

- name: bring wireguard up
  when: "cmd is not defined or cmd == 'up'"
  include_tasks: up.yml

- name: generate wireguard user configs on localhost
  when: "cmd is defined and cmd == 'userconfigs'"
  include_tasks: userconfigs.yml
